export const SCRIPTING_COMMANDS = new Set(['EVAL', 'EVALSHA', 'SCRIPT']);

export const SCRIPTABLE_COMMANDS = new Set([
  'PING', 'ECHO', 'GET', 'SET', 'SETEX', 'STRLEN', 'MGET', 'MSET', 'MSETNX',
  'DEL', 'UNLINK', 'EXISTS', 'TYPE', 'OBJECT', 'DBSIZE', 'SCAN', 'KEYS', 'RENAME',
  'EXPIRE', 'PEXPIRE', 'TTL', 'PTTL', 'PERSIST', 'INCR', 'DECR', 'INCRBY', 'DECRBY',
  'HSET', 'HSETNX', 'HMSET', 'HGET', 'HMGET', 'HGETALL', 'HKEYS', 'HVALS', 'HDEL',
  'HLEN', 'HEXISTS', 'HINCRBY', 'HINCRBYFLOAT', 'HSTRLEN', 'HSCAN', 'HRANDFIELD',
  'HEXPIRE', 'HPEXPIRE', 'HEXPIREAT', 'HPEXPIREAT', 'HTTL', 'HPTTL',
  'HEXPIRETIME', 'HPEXPIRETIME', 'HPERSIST',
  'SADD', 'SREM', 'SMEMBERS', 'SISMEMBER', 'SMISMEMBER', 'SCARD', 'SPOP', 'SRANDMEMBER',
  'LPUSH', 'RPUSH', 'LLEN', 'LRANGE', 'LINDEX', 'LPOP', 'RPOP', 'LREM', 'LSET', 'LTRIM', 'LMPOP',
  'ZADD', 'ZREM', 'ZCARD', 'ZSCORE', 'ZMSCORE', 'ZMPOP', 'ZRANGE', 'ZRANGEBYSCORE',
  'ZREVRANGE', 'ZREVRANGEBYSCORE', 'ZREVRANK', 'ZRANK', 'ZCOUNT', 'ZINCRBY',
  'ZREMRANGEBYRANK', 'ZREMRANGEBYSCORE',
]);
